### ISSUE TITLE
Duo push with no javascript popup

### ISSUE THREAD

**Issue by ckmaresca** [duosecurity/duo_php#10]
I have a situation where I want to use Duo as part of a backend API - there is no front end for Javascript to execute in.   What I'd like to do is push an auth to the phone, in the same way you can do it silently for SSH etc.

It's unclear how to do this in the current PHP SDK - is there a way?

**Comment by BradleyHiggins** [comment]
Duo has an Authentication API which enables you to handle this use case.  You can learn more about the Auth API at https://www.duosecurity.com/docs/authapi.

Please also check out our github repo https://github.com/duosecurity/duo_api_php, which handles some of the trickier parts of making calls to Duo's API from a PHP backend.

Thanks for using Duo!

**Comment by ckmaresca** [comment]
I can't comment on this as you all have deleted all issue reporting on 
GitHub, which is really, really obnoxious and unfriendly, never mind 
against security transparency principles.

The Duo API SDK requires PHP 5.6 and I don't see why. And there is now 
no forum to ask any questions.

Honestly, your lack of community friendliness is pushing me to look for 
another solution (even as a long-time Duo supporter).  I understand 
wanting to push people towards your paid support, but this is absurd.

Chris.

-- 
Chris Maresca <ckm@sherbit.io>
CTO - Sherbit - www.sherbit.io

**Comment by BradleyHiggins** [comment]
Hi Chris,
  For support issues, please e-mail support@duosecurity.com.  All Duo
users, including our free tier customers, can get support by e-mailing this
address.  Duo's support staff don't monitor the GitHub repos.  Closing the
issues tabs in GitHub is merely an attempt to ensure all support issues get
prompt attention from Duo's dedicated support staff.

  With regard to the Duo API SDK, the repo is open for pull requests.  We
would be delighted to see a pull request that makes the code compatible
with other versions of PHP.

Thanks,
Brad



On Mon, Aug 10, 2015 at 6:47 PM, Chris Maresca <notifications@github.com>
wrote:

> I can't comment on this as you all have deleted all issue reporting on
> GitHub, which is really, really obnoxious and unfriendly, never mind
> against security transparency principles.
>
> The Duo API SDK requires PHP 5.6 and I don't see why. And there is now
> no forum to ask any questions.
>
> Honestly, your lack of community friendliness is pushing me to look for
> another solution (even as a long-time Duo supporter). I understand
> wanting to push people towards your paid support, but this is absurd.
>
> Chris.
>
> --
> Chris Maresca <ckm@sherbit.io>
> CTO - Sherbit - www.sherbit.io
>
> On 8/10/15 1:48 PM, BradleyHiggins wrote:
> > Duo has an Authentication API which enables you to handle this use case.
> > You can learn more about the Auth API at
> > https://www.duosecurity.com/docs/authapi.
> >
> > Please also check out our github repo
> > https://github.com/duosecurity/duo_api_php, which handles some of the
> > trickier parts of making calls to Duo's API from a PHP backend.
> >
> > Thanks for using Duo!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/duosecurity/duo_php/issues/10#issuecomment-129602150
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duosecurity/duo_php/issues/10#issuecomment-129637236>.
>



-- 

*Brad Higgins*
/ Engineering Manager


brad@duosecurity.com


duosecurity.com

**Comment by ckmaresca** [comment]
There is no support available by email for free tiers:

https://www.duosecurity.com/support

And you've removed community support.

Shitty move.

Chris.


==
Chris Maresca
ckm@chrismaresca.com / +1.415.305.4496 / www.chrismaresca.com
skype: ckmaresca  / LinkedIn www.linkedin.com/in/chrismaresca
