### ISSUE TITLE
Expiration time issue

### ISSUE THREAD

**Issue by sportarc** [duosecurity/duo_php#6]
Hello,

I have some wierd issue going on with the DUO_EXPIRE time.
Locally things work great, but when I push the same code out to my AWS EC2 instance it doesn't work.

The AUTH expire time is always greater then the APP expire time.
This code below in the method 'parse_vals' always return null.
    if ($ts >= intval($exp)) {
			return null;
    }

I printed out the time in the logs and I get this:
ts: 1420607525 > exp: 1420607494

The expire time extracted from the base_64 string in the sig_response POST value is always behind in the remote host when locally it's ahead by few seconds. Locally I got this:
ts: 1420607337 > exp: 1420607396

I tried increasing the constant DUO_EXPIRE, but it doesn't change anything.

I am clueless right now. The only different I see it that my remote instance uses UTC time when locally I'm in EST time. I believe Duo generates this AUTH time so maybe it is something on your end? Or I am missing something ...

If you have any idea I'd greatly appreciate.

Thank you

**Comment by JackWink** [comment]
Are you using NTP on your EC2 instance? If your clock is even a few seconds out of sync, you can run in to some issues.

**Comment by sportarc** [comment]
I was not using it apparently. I just installed it and set it up.
Still running into the problem though.

I'll keep digging. Any other possibilities?

Thanks for the help.

On Wed, Jan 7, 2015 at 9:39 AM, Jack Wink <notifications@github.com> wrote:

> Are you using NTP on your EC2 instance? If your clock is even a few
> seconds out of sync, you can run in to some issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duosecurity/duo_php/issues/6#issuecomment-69029920>.
>



-- 
Nicolas Menciere
Founder and CTO
Sport Archive Inc.

**Comment by sportarc** [comment]
You were right.
Just bounced NTP and it works now

Thank you

On Sat, Jan 10, 2015 at 1:25 AM, Nicolas Menciere <nmenciere@sportarchive.tv
> wrote:

> I was not using it apparently. I just installed it and set it up.
> Still running into the problem though.
>
> I'll keep digging. Any other possibilities?
>
> Thanks for the help.
>
> On Wed, Jan 7, 2015 at 9:39 AM, Jack Wink <notifications@github.com>
> wrote:
>
>> Are you using NTP on your EC2 instance? If your clock is even a few
>> seconds out of sync, you can run in to some issues.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/duosecurity/duo_php/issues/6#issuecomment-69029920>.
>>
>
>
>
> --
> Nicolas Menciere
> Founder and CTO
> Sport Archive Inc.
>



-- 
Nicolas Menciere
Founder and CTO
Sport Archive Inc.

**Comment by mschwager** [comment]
Thanks for the heads up!
